server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/orderflo?createDatabaseIfNotExist=true&nullNamePatternMatchesAll=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=4096&prepStmtCacheSqlLimit=4096&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    
  jpa:
     hibernate:
      ddl-auto: update
     properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false

logging:
  file: c:/EDMT_WORK/orderflo.log
  level:
    co.hooghly.commerce.orderflo.business: info
    org.springframework.security: debug            

security:
  basic:
    enabled: false
management:
  security:
    enabled: false 
    
orderflo:
  mode: DEV               


  
  
