server:
  port: 80
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/commerce?createDatabaseIfNotExist=true&nullNamePatternMatchesAll=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=4096&prepStmtCacheSqlLimit=4096&zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
  

logging:
  file: c:/EDMT_WORK/commerce.log
  level:
   # org.elasticsearch: DEBUG  
    org.springframework.data.elasticsearch : WARN      
    org.springframework.security : WARN   
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.hibernate.type: TRACE            

security:
  basic:
    enabled: false
management:
  security:
    enabled: false                

secretKey: 7070200000000007

mailSender: 
  protocol: smtps
  host: smtp.gmail.com
  port: 465
  username: youremail@gmail.com
  password: yourpassword
  mail:
    smtp:
      auth: true
mail:
  smtp:
    starttls:
      enable: true

commerce:
  theme: zap
  
## Control controller start stop
hooghly:
  shop:
    controller:
      enabled: true   
  admin:
    controller:
      enabled : false  