server:
  port: 80
  context-path: /admin
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/commerce?createDatabaseIfNotExist=true&nullNamePatternMatchesAll=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=4096&prepStmtCacheSqlLimit=4096&zeroDateTimeBehavior=convertToNull&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
  

logging:
  file: ./commerce-admin.log
  level:
    org.springframework.security : WARN   
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.hibernate.type: TRACE            

security:
  basic:
    enabled: false
management:
  security:
    enabled: false                
